version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: video_interview_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: video_interview
    ports:
      - "3307:3306"
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
